remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme # add this line if it's not already present

title: "Wilson Ibe's GitHub Actions Site"
description: "This website is automatically deployed using GitHub Actions and Jekyll."
show_downloads: false # Set to true if you want download links
