name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Should deploy when main branch is updated
    paths:
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: main     # Deploys to main
          folder: .    # Deploy the root directory

